apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
data:
{{- with .Values.db }}
{{- with .user }}
  DB_USER: "{{ . | b64enc }}"
{{- end }}
{{- with .password }}
  DB_PASSWORD: "{{ . | b64enc }}"
{{- end }}
{{- end }}
{{- with .Values.roDb }}
{{- with .user }}
  RO_DB_USER: "{{ . | b64enc }}"
{{- end }}
{{- with .password }}
  RO_DB_PASSWORD: "{{ . | b64enc }}"
{{- end }}
{{- end }}
