# Default values for todo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:
  replicaCount: 3
  image:
    repository: cr.yandex/crpnl3q3e9hs5sr3088m/app/todo-backend
    tag: ""

  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 2000m
      memory: 1024Mi

  migrations:
    resources: 
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

frontend:
  replicaCount: 1
  image:
    repository: cr.yandex/crpnl3q3e9hs5sr3088m/app/todo-frontend
    tag: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
